### ISSUE TITLE
Improve dap-mode extension to use Camel debug adapter in Emacs

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-dap-client-emacs#1]
https://emacs-lsp.github.io/dap-mode/page/adding-debug-server/

note that in our case for `dap-register-debug-provider`, the parameter `:dap-server-path` must be used (and not `:debugPort` and `:host`)

A good example to get inspiration from is the Java debugger https://github.com/emacs-lsp/lsp-java/blob/master/dap-java.el

Given that Came debugger supports only attach mode for now. Seems the most important part is https://github.com/emacs-lsp/lsp-java/blob/a1aff851bcf4f397f2a968557d213db1fede0c8a/dap-java.el#L196

and update the readme in this repository to provide information to use it

**Comment by Navyashree0923** [comment]
Hello @yyoncho I have created a file dap-camel.el and I have placed this file under "~/.emacs.d/"

This is the content my dap-camel.el file.
```
(dap-register-debug-provider
 "camel"

 (lambda (conf)
 (plist-put conf :host "localhost")
   conf))

(dap-register-debug-template "camel example configuration"
			  
                             (list :type "camel"
                                   :request "attach"
                                   :args ""
				   :dap-server-path "java -jar /home/npr/Downloads/camel-dap-server-0.4.0.jar"
                                   :name "Run Configuration"))
(setq debug-on-error t)
```
When I run M-x:dap-debug. I can see this error 
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
make-process(:name "Run Configuration" :connection-type pipe :coding no-conversion :command "java -jar /home/npr/Downloads/camel-dap-server-0.4..." :stderr "*Run Configuration stderr*" :noquery t)
dap--create-session((:type "camel" :request "attach" :args "" :dap-server-path "java -jar /home/npr/Downloads/camel-dap-server-0.4..." :name "Run Configuration" :host "localhost"))
```
Could you please me understand how should I proceed further on this issue?
Thanks in advance

**Comment by yyoncho** [comment]
`:command` should be list, not string

**Comment by Navyashree0923** [comment]
` :dap-server-path '("java" "-jar" "/home/npr/Downloads/camel-dap-server-0.4.0.jar")`. But I still have some difficulties attaching camel-dap-server. I'm planning to look at the dap logs to understand what is going wrong here. Please if you have any suggestions let me know.

**Comment by Navyashree0923** [comment]
Thanks @yyoncho 
Debug Adapter support for Emacs editor is working now :)
